name: "TARS AI"
version: "1.0.1"
slug: "tarsha_ai"
description: "Run TARS-AI assistant inside Home Assistant"
startup: services
boot: auto
arch:
  - amd64
  - aarch64


# 👇 This adds the input field
options:
  openai_api_key: "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"

schema:
  openai_api_key: "str"

image: "trevlars/tars-ai:1.0.1"