name: "TARS AI"
version: "1.0.1"
slug: "tarsha_ai"
description: "Run TARS-AI assistant inside Home Assistant"
startup: services
boot: auto
arch:
  - amd64
  - aarch64

options:
  openai_api_key: "your-api-key-here"

schema:
  openai_api_key: str

image: "trevlars/tars-ai:1.0.1"